import { ReactNode } from "react";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { GroceryProvider } from "@/context/GroceryContext";
import { AuthProvider } from "@/app/utils/authContext";
import { UserProvider } from "@/context/UserProvider";
import { InventoryProvider } from "@/context/InventoryContext";

const poppins = Poppins({
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Meal Minder",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
<<<<<<< HEAD
        {/* <AuthProvider> */}
        <UserProvider>
          <GroceryProvider>{children}</GroceryProvider>
        </UserProvider>
        {/* </AuthProvider> */}
=======
        <AuthProvider>
          <UserProvider>
            <GroceryProvider>
              <InventoryProvider>{children}</InventoryProvider>
            </GroceryProvider>
          </UserProvider>
        </AuthProvider>
>>>>>>> ec488d94204682815f9c4b0137e65af905810820
      </body>
    </html>
  );
}
