import { ReactNode } from "react";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { GroceryProvider } from "@/context/GroceryContext";
import { AuthProvider } from "@/app/utils/authContext";

const poppins = Poppins({
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <AuthProvider>
          <GroceryProvider>{children}</GroceryProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
